spring:
  application:
    name: autheserver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    hostname: autheserver
    #prefer-ip-address: true
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  servlet:
    context-path: /auth

