server:
  port: 5565

management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    hostname: gatewayserver
    #prefer-ip-address: true

security:
  oauth2:
    resource:
      service-id: autheserver
      user-info-uri: http://autheserver:8768/auth/user  # 验证令牌