spring:
  application:
    name: configserver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    #prefer-ip-address: true
    health-check-url-path: /actuator/health
    hostname: configserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
