spring:
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mieandu.userservice.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis输出日志

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health